### PR TITLE
Add view filter

### LINKED ISSUE #8: Support feed.view
We need to be able to subscribe to [changes in a view](http://docs.couchdb.org/en/2.0.0/api/database/changes.html).

### PR DESCRIPTION
**Pull request by ceremcem**
Thanks for your hard work, please ensure all items are complete before opening.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://github.com/cloudant-labs/cloudant-follow/blob/master/DCO1.1.txt)

Resolves #8.

### CODE REVIEW

**Comment by smithsz** [comment]
+1, thanks for doing this @ceremcem. Can you please squash the later commits into b5bf4dd?

Apologies for the failing build. It can be a bit flakey!

**Comment by ceremcem** [comment]
Hmm, I've never used `git rebase` before, it seems pretty handy :)

**Comment by smithsz** [comment]
Thanks, one last thing... I've updated your PR description to include a tick box. Please check the top one to sign-off your agreement to the DCO.

**Comment by ceremcem** [comment]
OK, I signed it off. I think we're good to go :)

But, if one takes this "agreement" seriously, than I would suggest some other procedure rather than this, because one might claim that he didn't checked that tick box by himself, but someone might edit his comment who has higher permissions on this repository.

**Comment by smithsz** [comment]
Yeah, it's far from perfect. The previous process was very long-winded and involved emailing signed PDFs about which seemed overkill for tiny PRs. I guess we need to find a middle ground. In the meantime you have my word I won't add another ticked checkbox saying IBM now owns your house ;)
Thanks again for this. I'll get a new release cut asap.

**Pull request merged**
